version: 2

models:
  - name: stg_crypto
    description: "Deduplicated staging layer"
    columns:
      - name: coin_id
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['bitcoin', 'ethereum']
      - name: current_price_usd
        tests:
          - not_null

  - name: daily_crypto_summary
    columns:
      - name: coin_id
        tests:
          - not_null
      - name: price_date
        tests:
          - not_null